services:
  db:
    image: postgres:15-alpine
    container_name: event_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: event_platform
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./event-platform
    container_name: event_backend
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/event_platform
      - DB_USER=admin
      - DB_PASS=adminpassword
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: event_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
